# Generated by Django 4.1.3 on 2022-11-06 09:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identity_document_url',
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document_back',
            field=models.FileField(null=True, upload_to=users.models.back_identity_document_path_name),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document_expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document_front',
            field=models.FileField(null=True, upload_to=users.models.front_identity_document_path_name),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document_number',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_photo',
            field=models.ImageField(upload_to='display_photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='proof_of_address_document',
            field=models.FileField(upload_to='proof_of_address/'),
        ),
    ]
