# Generated by Django 4.1.3 on 2022-11-22 05:09

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_identity_document_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agency',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_number', models.CharField(max_length=65, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('reference_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('registered_name', models.CharField(max_length=500, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_logo', models.ImageField(upload_to='company_logo/')),
                ('certificate_of_incorporation', models.FileField(upload_to='certificate_of_incorporation/')),
                ('bank_information', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
    ]
