# Generated by Django 4.1.5 on 2023-02-21 18:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nationality_alter_user_secondary_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stages_of_profile_completion',
            field=models.JSONField(default=users.models.stagesOfProfileCompletion),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SHAREHOLDER', 'ShareHolder/Customers/Buyers'), ('AGENT', 'Real Estate Agent')], default='SHAREHOLDER', max_length=255),
        ),
    ]
