# Generated by Django 4.1.5 on 2023-01-04 19:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('completion_status', models.CharField(choices=[('IN-PROGRESS', 'construction in progress'), ('COMPLETED', 'contruction completed')], default='IN-PROGRESS', max_length=255)),
                ('apartment_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('percentage_discount', models.PositiveIntegerField(null=True)),
                ('promotion_closing_date', models.DateField(null=True)),
                ('promotion_type', models.CharField(blank=True, max_length=255)),
                ('other_deals', models.TextField(blank=True)),
                ('number_of_bedrooms', models.PositiveIntegerField(null=True)),
                ('number_of_toilets', models.PositiveIntegerField(null=True)),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('ERF_size', models.CharField(blank=True, max_length=256)),
                ('dining_area', models.CharField(blank=True, max_length=256)),
                ('cross_streets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('landmarks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('floor_size', models.CharField(blank=True, max_length=255)),
                ('date_built', models.DateField(null=True)),
                ('price_per_share', models.PositiveBigIntegerField(null=True)),
                ('completion_cost', models.PositiveBigIntegerField(null=True)),
                ('completion_date', models.DateField(null=True)),
                ('percentage_completed', models.PositiveIntegerField(null=True)),
                ('zip_code', models.PositiveIntegerField(null=True)),
                ('total_number_of_shares', models.PositiveIntegerField(null=True)),
                ('total_property_cost', models.PositiveBigIntegerField(null=True)),
                ('expected_ROI', models.PositiveBigIntegerField(null=True)),
                ('area_rent_rolls', models.CharField(blank=True, max_length=255)),
                ('scheduled_stays', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None), default=list, size=None)),
                ('other_incentives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'db_table': 'ShoppingCart',
            },
        ),
    ]
