# Generated by Django 4.1.5 on 2023-01-04 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='property',
            name='document_album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_album', to='album.mediaalbum'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='album.mediaalbum'),
        ),
    ]
