# Generated by Django 4.1.3 on 2022-12-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='listing_date',
        ),
    ]
