# Generated by Django 4.1.5 on 2023-01-10 22:12

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_image',
            field=models.ImageField(null=True, upload_to=properties.models.get_default_image_upload_path),
        ),
    ]
