# Generated by Django 4.1.5 on 2023-01-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_property_default_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('agent_firstname', models.CharField(blank=True, max_length=256, null=True)),
                ('agent_lastname', models.CharField(blank=True, max_length=256, null=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('client_firstname', models.CharField(blank=True, max_length=256, null=True)),
                ('client_lastname', models.CharField(blank=True, max_length=256, null=True)),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Agent Is yet to accept request'), ('CANCELLED', 'Client cancelled visitation request'), ('REJECTED', 'Agent rejected visitation schedule'), ('ACCEPTED', 'Agent accepted visitation schedule')], default='PENDING', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'db_table': 'PropertyInspections',
            },
        ),
    ]
