# Generated by Django 4.1.5 on 2023-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinspection',
            name='inspection_date',
            field=models.DateTimeField(),
        ),
    ]
