# Generated by Django 4.1.7 on 2023-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyinspection_inspection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approved_survey_plan',
            field=models.FileField(null=True, upload_to='approved_survey_plan/'),
        ),
        migrations.AddField(
            model_name='property',
            name='certificate_of_occupancy',
            field=models.FileField(null=True, upload_to='certificate_of_occupancy/'),
        ),
        migrations.AddField(
            model_name='property',
            name='excision_document',
            field=models.FileField(null=True, upload_to='excision_document/'),
        ),
        migrations.AddField(
            model_name='property',
            name='gazette_document',
            field=models.FileField(null=True, upload_to='gazette_document/'),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_receipt',
            field=models.FileField(null=True, upload_to='purchase_receipt/'),
        ),
        migrations.AddField(
            model_name='property',
            name='registered_deed_of_assignment',
            field=models.FileField(null=True, upload_to='registered_deed_of_assignment/'),
        ),
    ]
