# Generated by Django 4.1.7 on 2023-08-21 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0007_alter_property_expected_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='percentage_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='stage',
            field=models.CharField(choices=[('LISTING', 'Property is in listing page'), ('MARKETPLACE', 'Property is in marketplace page')], default='LISTING', max_length=255),
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=256)),
                ('social_link', models.URLField()),
                ('reason_for_purchase', models.CharField(max_length=256)),
                ('percentage_ownership', models.IntegerField()),
                ('price', models.FloatField()),
                ('intent_for_full_ownership', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Admin Is yet to review request'), ('REJECTED', 'Admin has rejected ownership request'), ('ACCEPTED', 'Admin has accepted ownership request')], default='PENDING', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PropertyOwnerships',
            },
        ),
    ]
