# Generated by Django 4.1.7 on 2023-08-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_percentage_sold_property_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownership',
            name='user_type',
            field=models.CharField(choices=[('HOME_OWNER', 'Property Owner/First buyer/Highest shareholder'), ('INVESTOR', 'Property Investor')], default='HOME_OWNER', max_length=256),
        ),
    ]
