# Generated by Django 4.1.7 on 2023-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyownership_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownership',
            name='expected_ROI',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='investment_focus',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='investment_timeline',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='investor_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='property',
            name='stage',
            field=models.CharField(choices=[('LISTING', 'Property is in listing page'), ('MARKETPLACE', 'Property is in marketplace page'), ('SOLD', 'Property has been sold off')], default='LISTING', max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='current_location',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='reason_for_purchase',
            field=models.CharField(default='', max_length=256),
        ),
    ]
