# Generated by Django 4.1.5 on 2023-01-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_propertyinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=256, null=True)),
                ('reference', models.CharField(max_length=256)),
                ('amount', models.PositiveBigIntegerField()),
                ('number_of_shares', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Successful Payment'), ('FAILED', 'Failed Payment')], default='PENDING', max_length=256)),
                ('payment_method', models.CharField(choices=[('PAYSTACK', 'Paystack Payment Service')], default='PAYSTACK', max_length=256)),
                ('error_message_from_payment_service', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs_agent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs_client', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'db_table': 'TransactionLogs',
            },
        ),
    ]
