# Generated by Django 4.1.3 on 2022-11-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_companyverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyVerification',
        ),
    ]
