# Generated by Django 4.1.5 on 2023-01-04 18:43

import album.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'MediaAlbums',
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=album.models.get_upload_path)),
                ('document', models.FileField(blank=True, null=True, upload_to=album.models.get_upload_path_for_document)),
                ('media_type', models.CharField(choices=[('IMAGE', 'images'), ('DOCUMENT', 'documents')], default='IMAGE', max_length=256)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='album.mediaalbum')),
            ],
            options={
                'db_table': 'MediaFiles',
            },
        ),
    ]
