# Generated by Django 4.1.5 on 2023-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user_role',
            field=models.CharField(choices=[('SHAREHOLDER', 'ShareHolder/Customers/Buyers'), ('AGENT', 'Real Estate Agent')], default='SHAREHOLDER', max_length=256),
        ),
    ]
